name: Build and publish testing image

on: [workflow_dispatch]

jobs:
  build-and-publish-testing-image:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: >
          pip install pip-tools

          pip-compile
          -o docker_testing_environment/requirements.txt
          --extra dev
          pyproject.toml


          docker buildx build
          -t ghcr.io/lukasturcani/stk-test-environment:latest
          ./docker_testing_environment

      - name: Publish image
        run: docker push
          ghcr.io/lukasturcani/stk-test-environment:latest
